Update main.yml

diff --git a/.github/workflows/main.yml b/.github/workflows/main.yml
--- a/.github/workflows/main.yml
+++ b/.github/workflows/main.yml
@@ -20,10 +20,9 @@ jobs:
         run: |
           npm install
       - name: Run deployment commands on server
-        run: |
-          ssh -o StrictHostKeyChecking=no ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_HOST }} << EOF
-            cd /path/to/your/project
-            git pull origin main
-            npm install
-            npm run build
+          run: |
+       ssh -i ${{ secrets.SERVER_KEY }} root@${{ secrets.SERVER_HOST }} << 'EOF'
+         cd ~/azmi || { echo "Directory not found"; exit 1; }
+         npm install || { echo "npm install failed"; exit 1; }
+        npm run build || { echo "npm run build failed"; exit 1; }
           EOF
